# sampling-based optimization
name: env_sbo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - casadi
  - matplotlib
  - pip
  - pinocchio
  - pip:
      - "jax[cuda12]"
      - mujoco>=3.4.0
      - mujoco-mjx>=3.4.0